global using System;
global using System.Text;
global using System.Threading.Tasks;
global using System.Linq;
global using System.Collections.Generic;
global using Common;
global using System.Numerics;
global using static Common.Maths;
global using Common.Extensions;
global using System.Text.RegularExpressions;
global using Combinatorics.Collections;